# Generated by Django 5.2.1 on 2025-06-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Id do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Rg do instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Nome do instrutor', max_length=70)),
                ('dataNascimento', models.DateField(help_text='Data de nascimento do instrutor')),
                ('telefone', models.CharField(help_text='Telefone do instrutor', max_length=9)),
                ('ddd', models.CharField(help_text='DDD do telefone do instrutor', max_length=3)),
            ],
        ),
    ]
