# Generated by Django 5.2.1 on 2025-06-06 23:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_instrutor_codigo_titul0_and_more'),
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrutor',
            name='codigo_titul0',
        ),
        migrations.AddField(
            model_name='instrutor',
            name='codigo_titulo',
            field=models.ForeignKey(blank=True, db_column='titulo_codigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='titulo.titulo'),
        ),
        migrations.AlterField(
            model_name='instrutor',
            name='dataNascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 6, 23, 55, 5, 532957, tzinfo=datetime.timezone.utc), help_text='Data de nascimento do instrutor', null=True),
        ),
    ]
