# Generated by Django 5.2.1 on 2025-06-09 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0003_remove_instrutor_codigo_titul0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='dataNascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 11, 28, 517723, tzinfo=datetime.timezone.utc), help_text='Data de nascimento do instrutor', null=True),
        ),
    ]
