# Generated by Django 5.2.1 on 2025-06-09 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0004_alter_instrutor_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='dataNascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 9, 22, 13, 25, 170431, tzinfo=datetime.timezone.utc), help_text='Data de nascimento do instrutor', null=True),
        ),
    ]
