# Generated by Django 5.2.1 on 2025-06-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tiposDeAtividade',
            fields=[
                ('codigo', models.AutoField(help_text='codigo do Tipo de Atividade', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='informe a descrição do Tipo de Atividade', max_length=70)),
            ],
        ),
    ]
