# Generated by Django 5.2.1 on 2025-06-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Matricula do aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do aluno', max_length=70)),
                ('dataInicial', models.DateField(help_text='Data inicial')),
                ('dataFinal', models.DateField(help_text='Data Final')),
            ],
        ),
    ]
