# Generated by Django 5.2.1 on 2025-06-06 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataFinal',
            field=models.DateField(blank=True, help_text='Informe a data Final de matrícula do aluno', null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 22, 7, 57, 333251, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial de matrícula do aluno'),
        ),
    ]
