# Generated by Django 5.2.1 on 2025-06-06 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_datafinal_alter_aluno_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 22, 45, 32, 817244, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial de matrícula do aluno'),
        ),
    ]
