# Generated by Django 5.2.1 on 2025-06-09 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_datainicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 22, 11, 28, 516722, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial de matrícula do aluno'),
        ),
    ]
