# Generated by Django 5.2.1 on 2025-06-09 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_datainicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='dataFinal',
            new_name='date_final',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='dataInicial',
        ),
        migrations.AddField(
            model_name='aluno',
            name='date_inicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 9, 22, 13, 25, 170431, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial de matrícula do aluno'),
        ),
    ]
