# Generated by Django 5.2.1 on 2025-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.AutoField(help_text='codigo do Titulo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='informe a descrição do titulo', max_length=70)),
            ],
        ),
    ]
