# Generated by Django 5.2.1 on 2025-06-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Numero da turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Horario da aula')),
                ('duracaoAula', models.SmallIntegerField(help_text='Duração da aula')),
                ('dataInicial', models.DateField(help_text='Data inicial')),
                ('dataFinal', models.DateField(help_text='Data Final')),
            ],
        ),
    ]
