# Generated by Django 5.2.1 on 2025-06-06 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_datainicial'),
        ('instrutor', '0003_remove_instrutor_codigo_titul0_and_more'),
        ('tiposdeatividade', '0002_alter_tiposdeatividade_descricao'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiposDeAtividade', to='tiposdeatividade.tiposdeatividade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Instrutor', to='instrutor.instrutor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aluno', to='aluno.aluno'),
        ),
    ]
