# Generated by Django 5.2.1 on 2025-06-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_turma_codigo_atividade_turma_id_instrutor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='dataFinal',
            new_name='date_final',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='dataInicial',
            new_name='date_inicial',
        ),
    ]
